framework:
    notifier:
        chatter_transports:
            slack: '%env(SLACK_DSN)%'
        channel_policy:
            high: ['chat/slack']
            low: ['email']
        admin_recipients:
            - { email: '%env(ADMIN_MAIL)%' }
